language: node_js
node_js:
  - "8"
  - "10"
before_script:
  - cp config.js.example config.js
script:
  - API_KEY=${API_KEY:-foo} npm test
  - npm run nsp
after_script:
  - npm run coveralls
notifications:
  email: false
  irc:
    channels:
      - "irc.w3.org#pub"
    skip_join: true
    template:
      - "%{branch} by %{author} (%{build_url}): %{message}"
